// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: AuctionHouse.proto

package AuctionHouse

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuctionService_SendBid_FullMethodName    = "/log.AuctionService/SendBid"
	AuctionService_SendResult_FullMethodName = "/log.AuctionService/SendResult"
)

// AuctionServiceClient is the client API for AuctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionServiceClient interface {
	SendBid(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UserBidRequest, BidResponse], error)
	SendResult(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResultResponse], error)
}

type auctionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionServiceClient(cc grpc.ClientConnInterface) AuctionServiceClient {
	return &auctionServiceClient{cc}
}

func (c *auctionServiceClient) SendBid(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UserBidRequest, BidResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuctionService_ServiceDesc.Streams[0], AuctionService_SendBid_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserBidRequest, BidResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuctionService_SendBidClient = grpc.BidiStreamingClient[UserBidRequest, BidResponse]

func (c *auctionServiceClient) SendResult(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResultResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuctionService_ServiceDesc.Streams[1], AuctionService_SendResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ResultResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuctionService_SendResultClient = grpc.ServerStreamingClient[ResultResponse]

// AuctionServiceServer is the server API for AuctionService service.
// All implementations must embed UnimplementedAuctionServiceServer
// for forward compatibility.
type AuctionServiceServer interface {
	SendBid(grpc.BidiStreamingServer[UserBidRequest, BidResponse]) error
	SendResult(*Empty, grpc.ServerStreamingServer[ResultResponse]) error
	mustEmbedUnimplementedAuctionServiceServer()
}

// UnimplementedAuctionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctionServiceServer struct{}

func (UnimplementedAuctionServiceServer) SendBid(grpc.BidiStreamingServer[UserBidRequest, BidResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendBid not implemented")
}
func (UnimplementedAuctionServiceServer) SendResult(*Empty, grpc.ServerStreamingServer[ResultResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendResult not implemented")
}
func (UnimplementedAuctionServiceServer) mustEmbedUnimplementedAuctionServiceServer() {}
func (UnimplementedAuctionServiceServer) testEmbeddedByValue()                        {}

// UnsafeAuctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionServiceServer will
// result in compilation errors.
type UnsafeAuctionServiceServer interface {
	mustEmbedUnimplementedAuctionServiceServer()
}

func RegisterAuctionServiceServer(s grpc.ServiceRegistrar, srv AuctionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuctionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuctionService_ServiceDesc, srv)
}

func _AuctionService_SendBid_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuctionServiceServer).SendBid(&grpc.GenericServerStream[UserBidRequest, BidResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuctionService_SendBidServer = grpc.BidiStreamingServer[UserBidRequest, BidResponse]

func _AuctionService_SendResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuctionServiceServer).SendResult(m, &grpc.GenericServerStream[Empty, ResultResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuctionService_SendResultServer = grpc.ServerStreamingServer[ResultResponse]

// AuctionService_ServiceDesc is the grpc.ServiceDesc for AuctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log.AuctionService",
	HandlerType: (*AuctionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendBid",
			Handler:       _AuctionService_SendBid_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendResult",
			Handler:       _AuctionService_SendResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "AuctionHouse.proto",
}
