// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.0--rc2
// source: AuctionHouse.proto

package AuctionHouse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// General response type
type GeneralResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*GeneralResponse_BidResponse
	//	*GeneralResponse_ResultResponse
	Response isGeneralResponse_Response `protobuf_oneof:"response"`
}

func (x *GeneralResponse) Reset() {
	*x = GeneralResponse{}
	mi := &file_AuctionHouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResponse) ProtoMessage() {}

func (x *GeneralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AuctionHouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResponse.ProtoReflect.Descriptor instead.
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return file_AuctionHouse_proto_rawDescGZIP(), []int{0}
}

func (m *GeneralResponse) GetResponse() isGeneralResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GeneralResponse) GetBidResponse() *BidResponse {
	if x, ok := x.GetResponse().(*GeneralResponse_BidResponse); ok {
		return x.BidResponse
	}
	return nil
}

func (x *GeneralResponse) GetResultResponse() *ResultResponse {
	if x, ok := x.GetResponse().(*GeneralResponse_ResultResponse); ok {
		return x.ResultResponse
	}
	return nil
}

type isGeneralResponse_Response interface {
	isGeneralResponse_Response()
}

type GeneralResponse_BidResponse struct {
	BidResponse *BidResponse `protobuf:"bytes,1,opt,name=bidResponse,proto3,oneof"`
}

type GeneralResponse_ResultResponse struct {
	ResultResponse *ResultResponse `protobuf:"bytes,2,opt,name=resultResponse,proto3,oneof"`
}

func (*GeneralResponse_BidResponse) isGeneralResponse_Response() {}

func (*GeneralResponse_ResultResponse) isGeneralResponse_Response() {}

type UserBidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidAmount  int32  `protobuf:"varint,1,opt,name=bidAmount,proto3" json:"bidAmount,omitempty"`
	BidderName string `protobuf:"bytes,2,opt,name=bidderName,proto3" json:"bidderName,omitempty"`
}

func (x *UserBidRequest) Reset() {
	*x = UserBidRequest{}
	mi := &file_AuctionHouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBidRequest) ProtoMessage() {}

func (x *UserBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AuctionHouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBidRequest.ProtoReflect.Descriptor instead.
func (*UserBidRequest) Descriptor() ([]byte, []int) {
	return file_AuctionHouse_proto_rawDescGZIP(), []int{1}
}

func (x *UserBidRequest) GetBidAmount() int32 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

func (x *UserBidRequest) GetBidderName() string {
	if x != nil {
		return x.BidderName
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_AuctionHouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_AuctionHouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_AuctionHouse_proto_rawDescGZIP(), []int{2}
}

type BidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack bool `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_AuctionHouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AuctionHouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_AuctionHouse_proto_rawDescGZIP(), []int{3}
}

func (x *BidResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type ResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Status     string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	WinnerName string `protobuf:"bytes,3,opt,name=WinnerName,proto3" json:"WinnerName,omitempty"`
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_AuctionHouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AuctionHouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_AuctionHouse_proto_rawDescGZIP(), []int{4}
}

func (x *ResultResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResultResponse) GetWinnerName() string {
	if x != nil {
		return x.WinnerName
	}
	return ""
}

var File_AuctionHouse_proto protoreflect.FileDescriptor

var file_AuctionHouse_proto_rawDesc = []byte{
	0x0a, 0x12, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x92, 0x01, 0x0a, 0x0f, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a,
	0x0b, 0x62, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x6f,
	0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4e,
	0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x69, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1f, 0x0a, 0x0b, 0x42, 0x69, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x60, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x7c, 0x0a, 0x0e, 0x41, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x69, 0x64, 0x12, 0x13, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6c,
	0x6f, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x0a, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x14, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2f, 0x41, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_AuctionHouse_proto_rawDescOnce sync.Once
	file_AuctionHouse_proto_rawDescData = file_AuctionHouse_proto_rawDesc
)

func file_AuctionHouse_proto_rawDescGZIP() []byte {
	file_AuctionHouse_proto_rawDescOnce.Do(func() {
		file_AuctionHouse_proto_rawDescData = protoimpl.X.CompressGZIP(file_AuctionHouse_proto_rawDescData)
	})
	return file_AuctionHouse_proto_rawDescData
}

var file_AuctionHouse_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_AuctionHouse_proto_goTypes = []any{
	(*GeneralResponse)(nil), // 0: log.GeneralResponse
	(*UserBidRequest)(nil),  // 1: log.UserBidRequest
	(*Empty)(nil),           // 2: log.Empty
	(*BidResponse)(nil),     // 3: log.BidResponse
	(*ResultResponse)(nil),  // 4: log.ResultResponse
}
var file_AuctionHouse_proto_depIdxs = []int32{
	3, // 0: log.GeneralResponse.bidResponse:type_name -> log.BidResponse
	4, // 1: log.GeneralResponse.resultResponse:type_name -> log.ResultResponse
	1, // 2: log.AuctionService.SendBid:input_type -> log.UserBidRequest
	2, // 3: log.AuctionService.SendResult:input_type -> log.Empty
	0, // 4: log.AuctionService.SendBid:output_type -> log.GeneralResponse
	0, // 5: log.AuctionService.SendResult:output_type -> log.GeneralResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AuctionHouse_proto_init() }
func file_AuctionHouse_proto_init() {
	if File_AuctionHouse_proto != nil {
		return
	}
	file_AuctionHouse_proto_msgTypes[0].OneofWrappers = []any{
		(*GeneralResponse_BidResponse)(nil),
		(*GeneralResponse_ResultResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AuctionHouse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AuctionHouse_proto_goTypes,
		DependencyIndexes: file_AuctionHouse_proto_depIdxs,
		MessageInfos:      file_AuctionHouse_proto_msgTypes,
	}.Build()
	File_AuctionHouse_proto = out.File
	file_AuctionHouse_proto_rawDesc = nil
	file_AuctionHouse_proto_goTypes = nil
	file_AuctionHouse_proto_depIdxs = nil
}
