syntax = "proto3";

package log;

option go_package = "/AuctionHouse";

service AuctionService {
    rpc SendBid(stream UserBidRequest) returns (stream GeneralResponse);
    rpc SendResult(Empty) returns (stream GeneralResponse);
}

// General response type 
message GeneralResponse {
        oneof response {
        BidResponse bidResponse = 1;
        ResultResponse resultResponse = 2;
    }
}

message UserBidRequest {
    int32 bidAmount = 1;
    string bidderName = 2;
}

message Empty {}

message BidResponse {
    bool ack = 1;
}

message ResultResponse {
    int32 result = 1;
    string status = 2;
    string WinnerName = 3;
}

